### ISSUE TITLE
Cannot delete a card

### ISSUE THREAD

**Issue by olisax** [belohoub/UBcards#8]
Hello!
I inserted an empty card by mistake, and I'm unable to delete it :-)
Is this somehow possible or not yet implemented?

**Comment by belohoub** [comment]
Hello, yes - it is implemented in line with Ubuntu Touch standard :-)
Just swipe the entry in the list to the left/right and action buttons will appear - as for many other native Ubuntu Touch apps. It's just not typical e.g. when coming from Android.

But be warned - there is "some" error, which causes, that deleting sometimes (unfortunately it's an "intermittent" error) causes deletion of another cad - I know about it, but I was not able even to start diagnostics due to my time limitations - I'll figure out in a future release, but I don't have a roadmap now :-(

**Comment by olisax** [comment]
Good, I managed to delete the empty record.
Thank's for your quick reply :-)
